[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.6.7"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200